name: Build and Deploy to dist Branch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 12.x

    steps:
    - name: Checkout
      uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: false
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm set audit false && node -v && npm -v
    - run: npm i
    - run: npm run build
    - name: Deploy
      run: |
        cd $GITHUB_WORKSPACE
        mkdir ./public-git
        cd ./public-git
        git init
        git config --global user.email "${CODING_EMAIL}"
        git config --global user.name "${CODING_USERNAME}"
        git remote add origin ${CODING_REPO}
        git checkout -b master
        cp -rf $GITHUB_WORKSPACE/public/* ./
        git add --all .
        DATE="$(echo $(TZ=UTC-8 date '+%Y-%m-%d %H:%M:%S'))"
        git commit -m "Deploy: $DATE"
        git push --quiet --force origin HEAD:master
      env:
        CODING_EMAIL: ${{ secrets.CODING_EMAIL }}
        CODING_USERNAME: ${{ secrets.CODING_USERNAME }}
        CODING_REPO: ${{ secrets.CODING_REPO }}
